"""Application-owned categories for Palworld server settings."""

from enum import Enum


class SettingCategory(str, Enum):
    GENERAL_WORLD_EVENTS = "General, World & Events"
    PLAYER_SURVIVAL_PROGRESSION = "Player Survival & Progression"
    PALS_CAPTURE_BREEDING = "Pals, Capture & Breeding"
    COMBAT_DAMAGE_RAIDS = "Combat, Damage & Raids"
    PVP_DEATH_RESPAWN = "PvP, Death & Respawn"
    BUILDING_BASES_GUILDS = "Building, Bases & Guilds"
    GATHERING_ITEMS_DROPS = "Gathering, Items & Drops"
    SERVER_IDENTITY_ACCESS_MULTIPLAYER = "Server Identity, Access & Multiplayer"
    NETWORK_API_RCON = "Network, API & RCON"
    VOICE_CHAT_ACCESSIBILITY = "Voice Chat & Accessibility"
    PERFORMANCE_LOGGING_BACKUPS = "Performance, Logging & Backups"
    ADVANCED_NEW_SETTINGS = "Advanced / New Settings"


CATEGORY_ORDER = tuple(SettingCategory)

CATEGORY_ICONS = {
    SettingCategory.GENERAL_WORLD_EVENTS: "🌍",
    SettingCategory.PLAYER_SURVIVAL_PROGRESSION: "🧍",
    SettingCategory.PALS_CAPTURE_BREEDING: "✨",
    SettingCategory.COMBAT_DAMAGE_RAIDS: "⚔️",
    SettingCategory.PVP_DEATH_RESPAWN: "☠️",
    SettingCategory.BUILDING_BASES_GUILDS: "🏗️",
    SettingCategory.GATHERING_ITEMS_DROPS: "📦",
    SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER: "🔐",
    SettingCategory.NETWORK_API_RCON: "🌐",
    SettingCategory.VOICE_CHAT_ACCESSIBILITY: "🔊",
    SettingCategory.PERFORMANCE_LOGGING_BACKUPS: "⚙️",
    SettingCategory.ADVANCED_NEW_SETTINGS: "🧩",
}

SETTING_CATEGORIES = {
    "AdditionalDropItemNumWhenPlayerKillingInPvPMode": SettingCategory.PVP_DEATH_RESPAWN,
    "AdditionalDropItemWhenPlayerKillingInPvPMode": SettingCategory.PVP_DEATH_RESPAWN,
    "AdminPassword": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "AllowConnectPlatform": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "AutoResetGuildTimeNoOnlinePlayers": SettingCategory.BUILDING_BASES_GUILDS,
    "AutoSaveSpan": SettingCategory.PERFORMANCE_LOGGING_BACKUPS,
    "AutoTransferMasterCheckIntervalSeconds": SettingCategory.PERFORMANCE_LOGGING_BACKUPS,
    "AutoTransferMasterThresholdDays": SettingCategory.PERFORMANCE_LOGGING_BACKUPS,
    "BanListURL": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "BaseCampMaxNum": SettingCategory.BUILDING_BASES_GUILDS,
    "BaseCampMaxNumInGuild": SettingCategory.BUILDING_BASES_GUILDS,
    "BaseCampWorkerMaxNum": SettingCategory.BUILDING_BASES_GUILDS,
    "BlockRespawnTime": SettingCategory.PVP_DEATH_RESPAWN,
    "BuildObjectDamageRate": SettingCategory.BUILDING_BASES_GUILDS,
    "BuildObjectDeteriorationDamageRate": SettingCategory.BUILDING_BASES_GUILDS,
    "BuildObjectHpRate": SettingCategory.BUILDING_BASES_GUILDS,
    "BuildingNameDisplayCacheTTLSeconds": SettingCategory.PERFORMANCE_LOGGING_BACKUPS,
    "ChatPostLimitPerMinute": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "CollectionDropRate": SettingCategory.GATHERING_ITEMS_DROPS,
    "CollectionObjectHpRate": SettingCategory.GATHERING_ITEMS_DROPS,
    "CollectionObjectRespawnSpeedRate": SettingCategory.GATHERING_ITEMS_DROPS,
    "CoopPlayerMaxNum": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "CrossplayPlatforms": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "DayTimeSpeedRate": SettingCategory.GENERAL_WORLD_EVENTS,
    "DeathPenalty": SettingCategory.PVP_DEATH_RESPAWN,
    "DenyTechnologyList": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "Difficulty": SettingCategory.GENERAL_WORLD_EVENTS,
    "DropItemAliveMaxHours": SettingCategory.GATHERING_ITEMS_DROPS,
    "DropItemMaxNum": SettingCategory.GATHERING_ITEMS_DROPS,
    "DropItemMaxNum_UNKO": SettingCategory.GATHERING_ITEMS_DROPS,
    "EnablePredatorBossPal": SettingCategory.COMBAT_DAMAGE_RAIDS,
    "EnemyDropItemRate": SettingCategory.GATHERING_ITEMS_DROPS,
    "EquipmentDurabilityDamageRate": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "ExpRate": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "GuildPlayerMaxNum": SettingCategory.BUILDING_BASES_GUILDS,
    "GuildRejoinCooldownMinutes": SettingCategory.BUILDING_BASES_GUILDS,
    "ItemContainerForceMarkDirtyInterval": SettingCategory.PERFORMANCE_LOGGING_BACKUPS,
    "ItemCorruptionMultiplier": SettingCategory.GATHERING_ITEMS_DROPS,
    "ItemWeightRate": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "LogFormatType": SettingCategory.PERFORMANCE_LOGGING_BACKUPS,
    "MaxBuildingLimitNum": SettingCategory.BUILDING_BASES_GUILDS,
    "MaxGuildsPerFrame": SettingCategory.BUILDING_BASES_GUILDS,
    "MonsterFarmActionSpeedRate": SettingCategory.PALS_CAPTURE_BREEDING,
    "NightTimeSpeedRate": SettingCategory.GENERAL_WORLD_EVENTS,
    "PalAutoHPRegeneRate": SettingCategory.PALS_CAPTURE_BREEDING,
    "PalAutoHpRegeneRateInSleep": SettingCategory.PALS_CAPTURE_BREEDING,
    "PalCaptureRate": SettingCategory.PALS_CAPTURE_BREEDING,
    "PalDamageRateAttack": SettingCategory.COMBAT_DAMAGE_RAIDS,
    "PalDamageRateDefense": SettingCategory.COMBAT_DAMAGE_RAIDS,
    "PalEggDefaultHatchingTime": SettingCategory.PALS_CAPTURE_BREEDING,
    "PalSpawnNumRate": SettingCategory.PALS_CAPTURE_BREEDING,
    "PalStaminaDecreaceRate": SettingCategory.PALS_CAPTURE_BREEDING,
    "PalStomachDecreaceRate": SettingCategory.PALS_CAPTURE_BREEDING,
    "PhysicsActiveDropItemMaxNum": SettingCategory.GATHERING_ITEMS_DROPS,
    "PlayerAutoHPRegeneRate": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "PlayerAutoHpRegeneRateInSleep": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "PlayerDamageRateAttack": SettingCategory.COMBAT_DAMAGE_RAIDS,
    "PlayerDamageRateDefense": SettingCategory.COMBAT_DAMAGE_RAIDS,
    "PlayerDataPalStorageUpdateCheckTickInterval": SettingCategory.PERFORMANCE_LOGGING_BACKUPS,
    "PlayerStaminaDecreaceRate": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "PlayerStomachDecreaceRate": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "PublicIP": SettingCategory.NETWORK_API_RCON,
    "PublicPort": SettingCategory.NETWORK_API_RCON,
    "RCONEnabled": SettingCategory.NETWORK_API_RCON,
    "RCONPort": SettingCategory.NETWORK_API_RCON,
    "RESTAPIEnabled": SettingCategory.NETWORK_API_RCON,
    "RESTAPIPort": SettingCategory.NETWORK_API_RCON,
    "RandomizerSeed": SettingCategory.GENERAL_WORLD_EVENTS,
    "RandomizerType": SettingCategory.GENERAL_WORLD_EVENTS,
    "Region": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "RespawnPenaltyDurationThreshold": SettingCategory.PVP_DEATH_RESPAWN,
    "RespawnPenaltyTimeScale": SettingCategory.PVP_DEATH_RESPAWN,
    "ServerDescription": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "ServerName": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "ServerPassword": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "ServerPlayerMaxNum": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "ServerReplicatePawnCullDistance": SettingCategory.PERFORMANCE_LOGGING_BACKUPS,
    "SupplyDropSpan": SettingCategory.GENERAL_WORLD_EVENTS,
    "VoiceChatMaxVolumeDistance": SettingCategory.VOICE_CHAT_ACCESSIBILITY,
    "VoiceChatZeroVolumeDistance": SettingCategory.VOICE_CHAT_ACCESSIBILITY,
    "WorkSpeedRate": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "bActiveUNKO": SettingCategory.GATHERING_ITEMS_DROPS,
    "bAdditionalDropItemWhenPlayerKillingInPvPMode": SettingCategory.PVP_DEATH_RESPAWN,
    "bAllowClientMod": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "bAllowEnhanceStat_Attack": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "bAllowEnhanceStat_Health": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "bAllowEnhanceStat_Stamina": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "bAllowEnhanceStat_Weight": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "bAllowEnhanceStat_WorkSpeed": SettingCategory.PLAYER_SURVIVAL_PROGRESSION,
    "bAllowGlobalPalboxExport": SettingCategory.PALS_CAPTURE_BREEDING,
    "bAllowGlobalPalboxImport": SettingCategory.PALS_CAPTURE_BREEDING,
    "bAutoResetGuildNoOnlinePlayers": SettingCategory.BUILDING_BASES_GUILDS,
    "bBuildAreaLimit": SettingCategory.BUILDING_BASES_GUILDS,
    "bCanPickupOtherGuildDeathPenaltyDrop": SettingCategory.PVP_DEATH_RESPAWN,
    "bCharacterRecreateInHardcore": SettingCategory.PVP_DEATH_RESPAWN,
    "bDisplayPvPItemNumOnWorldMap_BaseCamp": SettingCategory.PVP_DEATH_RESPAWN,
    "bDisplayPvPItemNumOnWorldMap_Player": SettingCategory.PVP_DEATH_RESPAWN,
    "bEnableAimAssistKeyboard": SettingCategory.VOICE_CHAT_ACCESSIBILITY,
    "bEnableAimAssistPad": SettingCategory.VOICE_CHAT_ACCESSIBILITY,
    "bEnableBuildingPlayerUIdDisplay": SettingCategory.BUILDING_BASES_GUILDS,
    "bEnableDefenseOtherGuildPlayer": SettingCategory.PVP_DEATH_RESPAWN,
    "bEnableFastTravel": SettingCategory.GENERAL_WORLD_EVENTS,
    "bEnableFastTravelOnlyBaseCamp": SettingCategory.GENERAL_WORLD_EVENTS,
    "bEnableFriendlyFire": SettingCategory.PVP_DEATH_RESPAWN,
    "bEnableInvaderEnemy": SettingCategory.COMBAT_DAMAGE_RAIDS,
    "bEnableNonLoginPenalty": SettingCategory.PVP_DEATH_RESPAWN,
    "bEnablePlayerToPlayerDamage": SettingCategory.PVP_DEATH_RESPAWN,
    "bEnableVoiceChat": SettingCategory.VOICE_CHAT_ACCESSIBILITY,
    "bExistPlayerAfterLogout": SettingCategory.PVP_DEATH_RESPAWN,
    "bHardcore": SettingCategory.PVP_DEATH_RESPAWN,
    "bInvisibleOtherGuildBaseCampAreaFX": SettingCategory.BUILDING_BASES_GUILDS,
    "bIsMultiplay": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "bIsPvP": SettingCategory.PVP_DEATH_RESPAWN,
    "bIsRandomizerPalLevelRandom": SettingCategory.GENERAL_WORLD_EVENTS,
    "bIsShowJoinLeftMessage": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "bIsStartLocationSelectByMap": SettingCategory.GENERAL_WORLD_EVENTS,
    "bIsUseBackupSaveData": SettingCategory.PERFORMANCE_LOGGING_BACKUPS,
    "bPalLost": SettingCategory.PVP_DEATH_RESPAWN,
    "bShowPlayerList": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
    "bUseAuth": SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER,
}


# Only settings with a meaningful workflow order are listed here. Settings not
# listed for a category are sorted alphabetically by their displayed name.
CATEGORY_SETTING_PRIORITY = {
    SettingCategory.GENERAL_WORLD_EVENTS: (
        "Difficulty",
        "DayTimeSpeedRate",
        "NightTimeSpeedRate",
        "RandomizerType",
        "RandomizerSeed",
        "bIsRandomizerPalLevelRandom",
        "bEnableFastTravel",
        "bEnableFastTravelOnlyBaseCamp",
        "bIsStartLocationSelectByMap",
        "SupplyDropSpan",
    ),
    SettingCategory.PLAYER_SURVIVAL_PROGRESSION: (
        "PlayerStomachDecreaceRate",
        "PlayerStaminaDecreaceRate",
        "PlayerAutoHPRegeneRate",
        "PlayerAutoHpRegeneRateInSleep",
        "bAllowEnhanceStat_Health",
        "bAllowEnhanceStat_Attack",
        "bAllowEnhanceStat_Stamina",
        "bAllowEnhanceStat_Weight",
        "bAllowEnhanceStat_WorkSpeed",
    ),
    SettingCategory.PALS_CAPTURE_BREEDING: (
        "PalCaptureRate",
        "PalSpawnNumRate",
        "PalEggDefaultHatchingTime",
        "MonsterFarmActionSpeedRate",
        "bAllowGlobalPalboxExport",
        "bAllowGlobalPalboxImport",
        "PalStomachDecreaceRate",
        "PalStaminaDecreaceRate",
        "PalAutoHPRegeneRate",
        "PalAutoHpRegeneRateInSleep",
    ),
    SettingCategory.COMBAT_DAMAGE_RAIDS: (
        "bEnableInvaderEnemy",
        "EnablePredatorBossPal",
        "PlayerDamageRateAttack",
        "PlayerDamageRateDefense",
        "PalDamageRateAttack",
        "PalDamageRateDefense",
    ),
    SettingCategory.PVP_DEATH_RESPAWN: (
        "bIsPvP",
        "bEnablePlayerToPlayerDamage",
        "bEnableDefenseOtherGuildPlayer",
        "bEnableFriendlyFire",
        "bExistPlayerAfterLogout",
        "bHardcore",
        "bCharacterRecreateInHardcore",
        "bPalLost",
        "DeathPenalty",
        "bCanPickupOtherGuildDeathPenaltyDrop",
        "bEnableNonLoginPenalty",
        "BlockRespawnTime",
        "RespawnPenaltyDurationThreshold",
        "RespawnPenaltyTimeScale",
        "bAdditionalDropItemWhenPlayerKillingInPvPMode",
        "AdditionalDropItemWhenPlayerKillingInPvPMode",
        "AdditionalDropItemNumWhenPlayerKillingInPvPMode",
        "bDisplayPvPItemNumOnWorldMap_Player",
        "bDisplayPvPItemNumOnWorldMap_BaseCamp",
    ),
    SettingCategory.BUILDING_BASES_GUILDS: (
        "BaseCampMaxNum",
        "BaseCampMaxNumInGuild",
        "BaseCampWorkerMaxNum",
        "GuildPlayerMaxNum",
        "GuildRejoinCooldownMinutes",
        "bAutoResetGuildNoOnlinePlayers",
        "AutoResetGuildTimeNoOnlinePlayers",
        "BuildObjectHpRate",
        "BuildObjectDamageRate",
        "BuildObjectDeteriorationDamageRate",
        "MaxBuildingLimitNum",
        "bBuildAreaLimit",
        "bEnableBuildingPlayerUIdDisplay",
        "bInvisibleOtherGuildBaseCampAreaFX",
    ),
    SettingCategory.SERVER_IDENTITY_ACCESS_MULTIPLAYER: (
        "ServerName",
        "ServerDescription",
        "ServerPassword",
        "AdminPassword",
        "bIsMultiplay",
        "ServerPlayerMaxNum",
        "CoopPlayerMaxNum",
        "CrossplayPlatforms",
        "AllowConnectPlatform",
        "bUseAuth",
        "bAllowClientMod",
        "BanListURL",
        "bShowPlayerList",
        "bIsShowJoinLeftMessage",
        "ChatPostLimitPerMinute",
    ),
    SettingCategory.NETWORK_API_RCON: (
        "PublicIP",
        "PublicPort",
        "RCONEnabled",
        "RCONPort",
        "RESTAPIEnabled",
        "RESTAPIPort",
    ),
    SettingCategory.VOICE_CHAT_ACCESSIBILITY: (
        "bEnableVoiceChat",
        "VoiceChatMaxVolumeDistance",
        "VoiceChatZeroVolumeDistance",
        "bEnableAimAssistPad",
        "bEnableAimAssistKeyboard",
    ),
    SettingCategory.PERFORMANCE_LOGGING_BACKUPS: (
        "bIsUseBackupSaveData",
        "AutoSaveSpan",
        "LogFormatType",
        "AutoTransferMasterCheckIntervalSeconds",
        "AutoTransferMasterThresholdDays",
    ),
}


def _validate_setting_priorities():
    for category, keys in CATEGORY_SETTING_PRIORITY.items():
        if len(keys) != len(set(keys)):
            raise ValueError(f"Duplicate sort priorities in {category.value}")
        for key in keys:
            if SETTING_CATEGORIES.get(key) is not category:
                raise ValueError(
                    f"{key} is prioritized under the wrong setting category"
                )


_validate_setting_priorities()
